name: Backend Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
               
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 1.11
              uses: actions/setup-java@v3
              with:
                  java-version: 1.11
                  
            - name: Build, so generates Coverage Report
              run: mvn -B package --file back/pom.xml
              
            - name: Upload Report
              uses: 'actions/upload-artifact@v4'
              with:
                name: jacoco-report
                path: ${{ github.workspace }}/back/target/site/jacoco/index.html

            - name: Add coverage to PR
              id: jacoco
              uses: madrapps/jacoco-report@v1.7.1
              with:
                  paths: ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  min-coverage-overall: 70
                  min-coverage-changed-files: 70
                  title: Code Coverage
