name: Frontend Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Comment Test Coverage
        uses: AthleticNet/comment-test-coverage@1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage/bobapp/coverage-summary.json
          title: Karma Test Coverage
