name: Main Workflow
on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
               
jobs:
    back-tests:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11.0
                  
            - name: Build with Maven
              run: mvn -B package --file back/pom.xml
              
            - name: Test with Maven
              run: mvn -B test --file back/pom.xml
              
            - name: Upload Reports
              uses: 'actions/upload-artifact@v4'
              with:
                  name: jacoco-report
                  path: ${{ github.workspace }}/back/target/site/jacoco
                
            - name: Add coverage to PR
              id: jacoco
              uses: madrapps/jacoco-report@v1.7.1
              with:
                  paths: ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  min-coverage-overall: 70
                  min-coverage-changed-files: 70

    front-tests:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: front
            
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}
    
          - run: npm ci
          - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

          - name: Upload Reports
            uses: 'actions/upload-artifact@v4'
            with:
                name: front-report
                path: ${{ github.workspace }}/front/coverage/bobapp
    
          - name: Comment Test Coverage
            uses: AthleticNet/comment-test-coverage@1.1
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              path: front/coverage/bobapp/coverage-summary.json
              title: Karma Test Coverage

    sonar-back:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            # Disabling shallow clones is recommended for improving the relevancy of reporting
            fetch-depth: 0
        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@<v5.0.0> 
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
            SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
          with:
            projectBaseDir: backend 
